### ISSUE TITLE
No lat-long for long press

### ISSUE THREAD

**Issue by fazlerabbi37** [mcastillof/FakeTraveler#1] opened 2018-07-28 12:25 UTC
First of thanks for this wonderful app. I was really excited to use it  but I couldn't because lat-long value was not found when long tap.

Step to reproduce:

- open the app
- zoom in to a place
- tap and hold on a place until a popup appears 
- click apply

Expected result:

Lat-Long appears in Lat-Lng field on the top bar and clicking 'Apply' should activate fake GPS.

Acctual result:

No Lat-Long appears on the top bar and clicking 'Apply' returns 'No Lat or Lng value. Long press in the map where you want to be located'

Please look into it. Thanks in advance!

**Comment by mcastillof** [comment] 2018-07-28 17:05
Thanks for reporting the issue. 
I will need more information as I couldn't reproduce the problem in my test environment (LineageOS 15.1 - API level 27).

* What's your Android version?
* Could you add a logcat? Please, kill the app, open it and try to long press on the map.

I will borrow a phone to give it a try.

**Comment by mcastillof** [comment] 2018-07-28 17:47
Ok. I confirmed the issue in Android 7.0.

**Comment by JonnyTech** [comment] 2018-07-28 17:51
Same problem here: LineageOS 14.1 (Android 7.1.2), API level 26, no google apps (microg). And the app keep stopping / crashing. What is the best way to get a logcat?

**Comment by mcastillof** [comment] 2018-07-28 21:41
I have pushed a quick fix to solve the problem. I'm closing the issue, but just feel free to reopen it if the problem persist. The app should be auto updated in F-Droid (probably in a few days). If you don't want to wait, you can always compile the app by yourself using Android Studio.

About getting a logcat, if you have Android Studio installed, and you have enabled developers options in your phone, there is a panel where you can see the logcat. If you don't have Android Studio, you may install Logcat Reader from F-Droid. That app can save a .txt file with the logcat. Just be sure to add a filter of using the application id, like cl.coders.faketravel for this app.

**Closed** 2018-07-28 21:41 UTC
Labels: bug

**Comment by JonnyTech** [comment] 2018-07-28 22:13
Thanks, I shall wait for f-droid to build it then report back.

**Comment by JonnyTech** [comment] 2018-07-30 18:39
Confirmed fixed with version 1.4 from F-droid - thanks!

**Comment by mcastillof** [comment] 2018-07-30 18:45
That's great!!

On July 30, 2018 2:39:08 PM GMT-04:00, JonnyTech <notifications@github.com> wrote:
>Confirmed fixed with version 1.4 from F-droid - thanks!
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/mcastillof/FakeTraveler/issues/1#issuecomment-408967149

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by europrimus** [comment] 2018-07-31 10:17
OK, now it work fine
thanks

**Comment by fazlerabbi37** [comment] 2018-07-31 10:28
Confirmed fixed.
